# .github/workflows/suggest-whitelist.yml
name: Suggest Pi-hole Whitelist Domains

# run manually or on a schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '30 04 * * 0'   # every Sunday at 04:30 local time

# (Optional) you can still lock down the GITHUB_TOKEN if you like,
# but we won’t actually use it for pushing or PRs in this job
permissions:
  contents: read
  pull-requests: read

env:
  BOT_PAT:       ${{ secrets.BOT_PAT }}
  BOT_NAME:      ${{ secrets.BOT_GIT_NAME }}
  BOT_EMAIL:     ${{ secrets.BOT_GIT_EMAIL }}

jobs:
  suggest-domains:
    name: Suggest new Pi-hole whitelist domains
    runs-on: [self-hosted, unraid, pihole]

    steps:
      - name: Check out with service account
        uses: actions/checkout@v4
        with:
          # use your PAT so that pushes/PRs are authenticated as the bot
          token: ${{ env.BOT_PAT }}
          fetch-depth: 0            # full history so branches can be pushed

      - name: Configure Git author
        run: |
          git config user.name  "${{ env.BOT_NAME }}"
          git config user.email "${{ env.BOT_EMAIL }}"

      - name: Extract suggested domains
        run: python3 scripts/suggest_whitelist.py

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          # again, use your PAT for authentication
          token:           ${{ env.BOT_PAT }}
          commit-message:  "chore: suggest new safe domains from Loki logs"
          title:           "chore: suggest new safe domains"
          body: |
            This PR was automatically generated by the GitHub Actions runner on Unraid.
            It includes domain suggestions pulled from Pi-hole logs via Loki.
            Please review and merge if appropriate.
          base:            main
          branch:          suggested-allowlist
          branch-suffix:   timestamp   # ensures a fresh branch name each run
          delete-branch:   false
