name: Suggest Safe Domains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 * *'  # 6:00 AM UTC on the 1st of every month

permissions:
  contents: write  # GITHUB_TOKEN limited on purpose since we use a PAT

jobs:
  suggest-domains:
    runs-on: [self-hosted, unraid, pi-hole]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "${{ secrets.BOT_GIT_NAME }}"
          git config user.email "${{ secrets.BOT_GIT_EMAIL }}"

      - name: Extract suggested domains and push branch
        run: |
          BRANCH_NAME="suggested-allowlist-$(date +'%Y-%m')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      
          # Create or update branch
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            git fetch origin "$BRANCH_NAME"
            git checkout "$BRANCH_NAME"
            git rebase "origin/$BRANCH_NAME"
          else
            git checkout -b "$BRANCH_NAME"
          fi
      
          python3 scripts/extract_safe_domains.py >> whitelist.txt
      
          git add whitelist.txt
          git commit -m "chore: suggest new safe domains from Loki logs"
          git push https://x-access-token:${{ secrets.BOT_PAT }}@github.com/justpow98/pihole-whitelist.git "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_PAT }}
          title: "chore: suggest new safe domains"
          body: |
            This PR was automatically generated by the GitHub Actions runner on Unraid.
            It includes domain suggestions pulled from Pi-hole logs via Loki.
            Please review and merge if appropriate.
          base: main
          branch: ${{env.BRANCH_NAME}}
