name: Suggest Safe Domains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 * *'

# —————————————————————————————————————————
# Limit the default GITHUB_TOKEN to read-only on contents
permissions:
  contents: read
# —————————————————————————————————————————

jobs:
  suggest-domains:
    runs-on: [self-hosted, unraid, pi-hole]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "AzuleLunaSvc"
          git config user.email "powersmjustin+svcacc@gmail.com"

      - name: Create branch for PR
        run: |
          export BRANCH_NAME="suggested-allowlist-$(date +'%Y-%m')"
          git checkout -b "$BRANCH_NAME"

      - name: Extract suggested domains from Loki logs
        run: |
          python3 scripts/extract_safe_domains.py >> whitelist.txt

      - name: Commit and push changes
        run: |
          BRANCH_NAME="suggested-allowlist-$(date +'%Y-%m')"
          git add whitelist.txt
          git commit -m "chore: suggest new safe domains from Loki logs"
          git push origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_PAT }}
          title: "chore: suggest new safe domains"
          body: |
            This PR was automatically generated by the GitHub Actions runner on Unraid.
            It includes domain suggestions pulled from Pi-hole logs via Loki.
            Please review and merge if safe.
          base: main
          branch: ${{ env.BRANCH_NAME }}
